### ISSUE TITLE
Using `hookFunction` via electron-winstaller

### ISSUE THREAD

**Issue by inukshuk** [electron/windows-sign#12]
Hi and thanks for the recent update to allow custom signing via electron-winstaller. The docs mention that `hookFunction` can only be used when calling the sign function directly and that `hookModulePath` should be used to override how other users (like electron-packager) do the signing. Do I read that correctly? Or is it possible to use `hookFunction` via electron-winstaller as well?

**Comment by inukshuk** [comment]
Thanks!

**Comment by barkinoaa** [comment]
Hi @MarshallOfSound! Thanks for your helpful reply. I tried using `hookModulePath` to implement my custom code-signing handler, but I encountered some issues. I came across an issue in the electron-windows-installer library regarding the usage of the 'windows-sign' parameter in the createWindowsInstaller function. It seems that this parameter throws an error in the 'SEA_MAIN_SCRIPT'. I created an issue for this in the electron-windows-installer library([here](https://github.com/electron/windows-installer/issues/508)). Do you have any suggestions on how to address this?
