### ISSUE TITLE
Support for Digicert Keylocker or other HSM service

### ISSUE THREAD

**Issue by busterbogheart** [electron/windows-sign#31]
Is this on the roadmap?  We are using Forge with windows-sign, and are looking for a solution to use with HSM/EV certs.

**Comment by felixrieseberg** [comment]
Hi! Good news: We fully support all those solutions! It depends a little on the specific provider which option is most useful, but in the case of Digicert Keylocker, you'll be able to use a custom `signtool.exe` provided by Digicert.

Then, you simply pass the path to that `signtool.exe` to `@electron/windows-sign` (https://github.com/electron/windows-sign?tab=readme-ov-file#with-a-custom-signtoolexe-or-custom-parameters) - and you should be good!

**Comment by felixrieseberg** [comment]
For some additional help, I'm adding more documentation: https://github.com/electron/windows-sign/pull/32

**Comment by busterbogheart** [comment]
Ok that looks good.  How can we integrate this method with Forge then?
